# Generated by Django 3.2.9 on 2022-08-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='resdate', to='projectapp.dates', to_field='date'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resdoctor', to='projectapp.user', to_field='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='treatment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='projectapp.treatment', to_field='treatment_name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='projectapp.user', to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateTimeField(default='', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('doctor', 'date')},
        ),
    ]
