# Generated by Django 3.2.9 on 2022-07-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Man'), (2, 'Woman'), (3, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User'), (3, 'Doctor')], default=2),
        ),
    ]
