# Generated by Django 3.2.9 on 2022-07-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20220719_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('pic_url', models.CharField(max_length=100)),
                ('treatment_description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
