# Generated by Django 3.2.9 on 2022-07-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='rating',
        ),
    ]
