# Generated by Django 3.2.9 on 2022-08-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20220829_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Doctor'), (4, 'Superadmin')], default=2),
        ),
    ]
