# Generated by Django 3.2.9 on 2022-08-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_ineligibledomain_mtokenrequest_tokenrequest_trainingspace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingSpace',
        ),
    ]
