# Generated by Django 3.2.9 on 2022-07-25 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_status', models.IntegerField(choices=[(1, 'Created'), (2, 'Accepted'), (3, 'Refused'), (4, 'Done')], default=1)),
                ('treatment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='projectapp.treatment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
