# Generated by Django 3.2.9 on 2022-08-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_delete_trainingspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='problem_description',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MAN', 'Man'), ('WOMAN', 'Woman'), ('OTHER', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
