# Generated by Django 3.2.9 on 2022-07-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='medical_note',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
