# Generated by Django 3.2.9 on 2022-07-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Accepted'), (3, 'Refused'), (4, 'Done')], default=1),
        ),
    ]
