# Generated by Django 3.2.9 on 2022-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_auto_20220809_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'Man'), (2, 'Woman'), (3, 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'Admin'), (2, 'User'), (3, 'Doctor')], default='', max_length=100),
        ),
    ]
