# Generated by Django 3.2.9 on 2022-07-25 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_reservation_medicla_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='medicla_note',
            new_name='medical_note',
        ),
        migrations.AddField(
            model_name='reservation',
            name='doctor_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctorchoicereservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
