# Generated by Django 3.2.9 on 2022-07-26 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_reservation_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='pic_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctor',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(db_column='emailVerified', default=False),
        ),
    ]
