# Generated by Django 3.2.9 on 2022-07-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_reservation_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='username',
            new_name='user',
        ),
    ]
