# Generated by Django 3.2.9 on 2022-07-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_reservation_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialisation',
            field=models.CharField(default='', max_length=65),
        ),
    ]
