# Generated by Django 3.2.9 on 2022-08-09 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_reservation_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='resdate', to='projectapp.dates'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='treatment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='projectapp.treatment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
    ]
