# Generated by Django 3.2.9 on 2022-08-09 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_reservation_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resdoctor', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
