# Generated by Django 3.2.9 on 2022-07-29 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_reservation_doctor'),
    ]

    operations = [

        migrations.AddField(
            model_name='user',
            name='specialisation',
            field=models.CharField(default='', max_length=120),
        ),

    ]
