# Generated by Django 3.2.9 on 2022-08-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_auto_20220809_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Man'), (2, 'Woman'), (3, 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User'), (3, 'Doctor')], default='', max_length=100),
        ),
    ]
