# Generated by Django 3.2.9 on 2022-08-01 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_auto_20220801_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resdoctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
