# Generated by Django 3.2.9 on 2022-08-01 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_auto_20220801_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resdoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resdate',
                                       to='projectapp.date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='hour',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hours',
                                       to='projectapp.hour'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resdate',
                                    to='projectapp.date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hours',
                                    to='projectapp.hour'),
        ),
    ]
