# Generated by Django 3.2.9 on 2022-08-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_auto_20220810_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='problem_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Accepted'), (3, 'Refusedbydoctor'), (4, 'Done'), (5, 'Refusedbyuser')], default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='treatment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='projectapp.treatment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='username'),
        ),
    ]
