# Generated by Django 3.2.9 on 2022-08-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_reservation_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resdate', to='projectapp.date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='hour',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='projectapp.hour'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'hour')},
        ),
    ]
