# Generated by Django 3.2.9 on 2022-08-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_reservation_doctor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('doctor', 'date', 'hour')},
        ),
    ]
