# Generated by Django 3.2.9 on 2022-08-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0013_auto_20220802_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(choices=[('1', 'Man'), ('2', 'Woman'), ('3', 'Other')], default='1'),
        ),
    ]
