# Generated by Django 3.2.9 on 2022-08-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_alter_treatment_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
