# Generated by Django 3.2.9 on 2022-08-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MAN', 'Man'), ('WOMAN', 'Woman'), ('OTHER', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('DOCTOR', 'Doctor')], default='', max_length=100),
        ),
    ]
