# Generated by Django 3.2.9 on 2022-08-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0018_auto_20220811_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='problem_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Accepted'), (3, 'Cancelledbydoctor'), (4, 'Done'), (5, 'Cancelledbyuser')], default=1),
        ),
    ]
