# Generated by Django 3.2.9 on 2022-08-16 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0019_auto_20220816_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ManyToManyField(related_name='treatment', to=settings.AUTH_USER_MODEL),
        ),
    ]
