# Generated by Django 3.2.9 on 2022-08-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0022_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.rating'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
