# Generated by Django 3.2.9 on 2022-08-17 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0023_auto_20220817_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.treatment'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'treatment')},
        ),
    ]
