# Generated by Django 3.2.9 on 2022-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0025_auto_20220817_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='rating',
        ),
        migrations.AddField(
            model_name='treatment',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, to='projectapp.Rating'),
        ),
    ]
