# Generated by Django 3.2.9 on 2022-08-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0026_auto_20220817_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='rating',
        ),
        migrations.AddField(
            model_name='treatment',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.rating'),
        ),
    ]
