# Generated by Django 3.2.9 on 2022-08-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0027_auto_20220817_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.treatment'),
        ),
    ]
