# Generated by Django 3.2.9 on 2022-08-18 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0030_alter_treatment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to=settings.AUTH_USER_MODEL),
        ),
    ]
