# Generated by Django 3.2.9 on 2022-08-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0031_alter_treatment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User'), (3, 'Doctor')], null=True),
        ),
    ]
